version: "3.9"
services:
  worker: Sivatheboss
    build: .
    environment:
      APP_ID: $API_ID
      API_HASH: $API_HASH
      OWNER_ID: $OWNER_ID
      OWNER_USERNAME: $OWNER_USERNAME
      SUPPORT_CHAT: $SUPPORT_CHAT
      SPAMWATCH_API: $SPAMWATCH_API
      DRAGONS: $DRAGONS
      DEV_USERS: $DEV_USERS
      DEMONS: $DEMONS
      WOLVES: $WOLVES
